# Numpy 

In [1]:
import numpy as np

myarr=np.array([[3,4,33,8]],np.int64)

In [2]:
myarr

array([[ 3,  4, 33,  8]], dtype=int64)

In [3]:
myarr[0,1]

4

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr[0,1]=50
myarr

array([[ 3, 50, 33,  8]], dtype=int64)


### Array creation: Conversion from other Python Structures 

In [8]:
listarr=np.array([[1,2,3],[4,5,6], [7,8,9]])

In [9]:
listarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
print(listarr.dtype)
print(listarr.shape)
print(listarr.size)

int32
(3, 3)
9


In [11]:
np.array({22,33,44})

array({33, 44, 22}, dtype=object)

In [12]:
zeros=np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
rng=np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
lspace=np.linspace(1,5,12)      #=>linspace(first elment, renage of elmetn, how many elment you have requred)
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [16]:
emp=np.empty((4,6))
emp

array([[1.30112574e-311, 7.50979782e-322, 0.00000000e+000,
        0.00000000e+000, 1.24610723e-306, 1.16095484e-028],
       [2.51313104e+180, 1.06318459e+248, 1.47169225e-052,
        6.01347022e-154, 7.35174777e+223, 5.30021788e+199],
       [3.81540411e+180, 2.13672204e+161, 1.42244599e+214,
        4.57221088e+228, 1.33516665e+179, 9.52387092e+228],
       [5.46655079e+241, 9.22800730e+135, 5.48108349e-143,
        2.91237123e+257, 4.71294503e+257, 1.35346062e+295]])

In [17]:
emp_like=np.empty_like(lspace)
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [18]:
ide=np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [19]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [22]:
arr=arr.reshape(3,33)

In [23]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [29]:
arr=arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [28]:
arr.shape

(99,)

In [57]:
x=[[10,2,3],[4,75,6],[7,8,9]]
ar=np.array(x)
ar

array([[10,  2,  3],
       [ 4, 75,  6],
       [ 7,  8,  9]])

In [33]:
ar.sum(axis=0)

array([12, 15, 18])

In [34]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [35]:
ar.T # ar.t whil be tronfose the matrix

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [37]:
ar.flat
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [38]:
ar.ndin

AttributeError: 'numpy.ndarray' object has no attribute 'ndin'

In [39]:
ar.size

9

In [40]:
ar.nbytes #how many bytes your array will consume

36

In [44]:
one=np.array([1,2,38,4,5,6])
one.argmax()

5

In [45]:
one.argmin()

0

In [46]:
one.argsort()

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [48]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
ar.argmin()

0

In [50]:
ar.argmax()

8

In [58]:
ar.argmax(axis=0)

array([0, 1, 2], dtype=int64)

In [59]:
ar.argmax(axis=1)

array([0, 1, 2], dtype=int64)

In [60]:
ar.argsort(axis=0)

array([[1, 0, 0],
       [2, 2, 1],
       [0, 1, 2]], dtype=int64)

In [61]:
ar.argsort(axis=1)

array([[1, 2, 0],
       [0, 2, 1],
       [0, 1, 2]], dtype=int64)

In [62]:
ar.ravel()

array([10,  2,  3,  4, 75,  6,  7,  8,  9])

In [65]:
ar2=np.array([[1, 2, 0],[0, 2, 1],[0, 1, 2]])

In [66]:
ar+ar2

array([[11,  4,  3],
       [ 4, 77,  7],
       [ 7,  9, 11]])

In [67]:
ar

array([[10,  2,  3],
       [ 4, 75,  6],
       [ 7,  8,  9]])

In [68]:
ar2

array([[1, 2, 0],
       [0, 2, 1],
       [0, 1, 2]])

In [69]:
ar*ar2

array([[ 10,   4,   0],
       [  0, 150,   6],
       [  0,   8,  18]])

In [70]:
np.sqrt(ar)

array([[3.16227766, 1.41421356, 1.73205081],
       [2.        , 8.66025404, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [71]:
ar.sum()

124

In [73]:
ar.max()

75

In [74]:
ar.min()

2

In [75]:
ar

array([[10,  2,  3],
       [ 4, 75,  6],
       [ 7,  8,  9]])

In [76]:
np.where(ar>5)

(array([0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [77]:
np.count_nonzero(ar)

9

In [78]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [79]:
import sys

In [80]:
py_ar=[0,4,55,2]

In [81]:
np_ar=np.array(py_ar)

In [82]:
sys.getsizeof(1)*len(py_ar)

112

In [83]:
np_ar.itemsize*np_ar.size

16